#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times.

# Initialize counter
counter=0

# Loop until counter reaches 10
while [ $counter -lt 10 ]; do
    echo "Best School"
    # Increment counter
    ((counter++))
done